import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Footer from "../components/Footer";

import Appbar from "./Appbar";

const name = "Your Name";
export const siteTitle = "Next.js Sample Website";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Raleway:wght@300&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <title>Rimufest Music Festival</title>
        <meta
          name="RimuFest Chamber Music Festival - a biannual summer music festival held in New Zealand and Mexico offering concert series and educational programs."
          content="Generated by create next app"
        />
      </Head>
      <Appbar />
      {children}
      <Footer />
    </>
  );
}
