import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { AppMenu } from "../components/AppMenu/AppMenu";
import Footer from "~/components/Footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="relative">
        <AppMenu />
        <main className="flex min-h-screen flex-col items-center justify-center bg-white text-black">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
