export const LangStrings = {
  nz: {
    nz2025: "Annual 2025",
    nz2024: "Annual 2024",
    pressRoom: "Press Room",
    holidayProgramme: "Holiday Programme",
    upcoming: "Upcoming",
    about: "About",
    concerts: "Concerts",
    programs: "Programmes",
    joinUs: "Join Us",
    gallery: "Gallery",
    artists: "Artists",
    violin: "violin",
    conductor: "conductor",
    percussion: "percussion",
    ensembleInResidence: "Ensemble in Residence at Rimufest",
    festivals: "Festivals",
    support: "Support",
    pressRoom: "Press Room",
    blurb:
      "We believe that by changing the perspective of music we can inspire the next generation to get creative in a way they can enjoy for the rest of their lives. By introducing string students of all abilities to an engaging, uplifting, and interactive way to learn new skills, we are proud to host a chamber music festival unlike any other. With locations in Mexico and New Zealand, our goal is to help students all over the world do more of what they love.",
  },
  mx: {
    pressRoom: "Press Room",
    upcoming: "Upcoming",
    nz2025: "Annual 2025",
    nz2024: "Annual 2024",
    holidayProgramme: "Holiday Programme",
    artists: "Artistas",
    about: "Acerca",
    concerts: "Conciertos",
    programs: "Programas",
    joinUs: "Únete",
    gallery: "Galería",
    violin: "violín",
    conductor: "director",
    percussion: "percussión",
    ensembleInResidence: "Ensamble en Residencia en Rimufest",
    festivals: "Festivales",
    pressRoom: "Prensa",
    support: "Apóyanos",
  },
};
